#!/usr/bin/env bash
# shellcheck disable=SC1091

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_DIR/helpers/messages.sh"

if [ -z "$ROOTFS" ]; then
	msg_error "Variável ROOTFS não definida."
	exit 1
fi

source "$SCRIPT_DIR/config.sh"
source "$SCRIPT_DIR/helpers/requirements.sh"

verify_dependencies

if [ "$I_KNOW_WHAT_I_DOING" = no ]; then
    verify_hardware
fi

main() {
    :
}

echo "passou"