#!/usr/bin/env bash
# shellcheck disable=SC1091

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

. "$SCRIPT_DIR/helpers/messages.sh"
. "$SCRIPT_DIR/config.sh"
. "$SCRIPT_DIR/helpers/check_requirements.sh"
. "$SCRIPT_DIR/helpers/utils.sh"
. "$SCRIPT_DIR/helpers/systree.sh"

info


#umount_nbd_image

preparation_workspace
prepare_environment

preparation_sysfile

file_interloper "Criando uma árvore de diretórios mínima" make_minimal_systree

build_interloper "Cabeçalhos do Kernel Linux" "$SCRIPT_DIR/recipes/phase1/cross_linux_headers.sh"

build_interloper "Cabeçalhos do Musl" "$SCRIPT_DIR/recipes/phase1/cross_musl_headers.sh"

echo "passou"